MODEL:
  PRETRAIN_CHOICE: 'pretrain'
  PRETRAIN_PATH: './logs/pretrain/deit_base/dr/ddr/transformer_best_model.pth'
  # PRETRAIN_PATH: './ckp/logs_0325_shot_gvp/uda/deit_base/dr/ddr2aptos/transformer_best_model.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  Transformer_TYPE: 'uda_vit_base_patch16_224_TransReID' #uda_vit_small_patch16_224_TransReID
  STRIDE_SIZE: [16, 16]
  BLOCK_PATTERN: '3_branches'
  # BLOCK_PATTERN: ''
  TASK_TYPE: 'classify_DA'
  UDA_STAGE: 'UDA'
#  CAMERA_EMBEDDING: True
#  VIEWPOINT_EMBEDDING: True

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  SIZE_CROP: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.0 # random erasing
  PADDING: 0
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATASETS:
  NAMES: ('Dr')
  ROOT_TRAIN_DIR: ('./data/Dr/aptos_saliency_list.txt')
  # ROOT_TRAIN_DIR: ('./data/Dr/ddr_list.txt')
  NAMES2: ('Dr')
  ROOT_TRAIN_DIR2: ('./data/Dr/aptos_list.txt')
  ROOT_TEST_DIR: ('./data/Dr/aptos_list.txt')

DATALOADER:
  SAMPLER: 'softmax'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MAX_EPOCHS: 1
  BASE_LR: 1e-5
  IMS_PER_BATCH: 64
  STEPS: [40, 80]
  PAR: 0.0001
  PAR_KL : 1.0
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 8
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 10
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  0.0
  WEIGHT_DECAY_BIAS: 5e-4
  BIAS_LR_FACTOR: 2
  WITH_PSEUDO_LABEL_FILTER: True

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  RE_RANKING_TRACK: False
  WEIGHT: '../logs/trans4DA/transformer_120.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './ckp/test/uda/deit_base/dr/ddr2aptos'
# OUTPUT_DIR: './ckp/log_0410_tent_gvp_new/uda/deit_base/dr/deepdr2messidor_2'
# PAR : 1